#!/bin/bash

# create a system user for the process, modern useradd will add the default group too
# Assume DDB home dir as default location
if [[ ! $(id appmetric2ddb 2>/dev/null) ]] ;then
    # create a appmetric2ddb system account
    /usr/sbin/useradd --system --create-home --home-dir /data/appmetric2ddb -s /bin/bash appmetric2ddb
fi
